In [1]:
import torch
torch.__version__

'2.1.2'

In [22]:
scalar=torch.tensor(7)
print(scalar)
print(scalar.item())
vector=torch.tensor([7,7])
print(vector)
matrix=torch.tensor([[7,8],
                     [9,10]])
print(matrix)
print(matrix.shape)
tensor=torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
print(tensor)
print(tensor.ndim)
print(len(tensor.shape))
print("num of ele: ",tensor.numel())

tensor(7)
7
tensor([7, 7])
tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
3
num of ele:  9


In [40]:
rand_tensor=torch.rand((3,4))
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.ndim)
print(rand_tensor.device)
zero_tensor = torch.zeros((3,4))
print(zero_tensor, zero_tensor.shape, zero_tensor.dtype)
ones_tensor = torch.ones((3,4))
print(ones_tensor, ones_tensor.shape, ones_tensor.dtype)

zero_to_ten= torch.arange(1,10,1)
print(zero_to_ten)
range_tensor = torch.zeros_like(zero_to_ten)
print(range_tensor)

tensor([[0.2107, 0.9890, 0.1654, 0.3997],
        [0.5559, 0.5148, 0.7077, 0.0636],
        [0.8443, 0.2271, 0.2249, 0.7048]])
torch.Size([3, 4])
torch.float32
2
cpu
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.Size([3, 4]) torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.Size([3, 4]) torch.float32
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


In [44]:
torch.cuda.is_available()
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)
print(torch.cuda.device_count())

cuda
1


In [62]:
#Q1
tensor=torch.tensor([[1,2,3],
                     [4,5,6]])
print(tensor, tensor.shape)
#reshaping
reshaped_tensor=torch.reshape(tensor,(3,2))
print(reshaped_tensor, reshaped_tensor.shape)
#squeezing
squeezed_tensor=tensor.reshape([1,6]).squeeze()
print(squeezed_tensor, squeezed_tensor.shape)
rand_tensor=torch.randint(1,10,(3,1,4))
print(rand_tensor.shape)
print(rand_tensor)
print(rand_tensor.squeeze())
print(rand_tensor.squeeze().shape)
#unsqueezing
unsqueezed_tensor=tensor.unsqueeze(0)
print(unsqueezed_tensor,unsqueezed_tensor.shape)
unsqueezed_tensor1=tensor.unsqueeze(-1)
print(unsqueezed_tensor1,unsqueezed_tensor1.shape)
unsqueezed_tensor2=squeezed_tensor.unsqueeze(1)
print(unsqueezed_tensor2,unsqueezed_tensor2.shape)
#stack
x=torch.tensor([1,2,3,4,5])
y=torch.tensor([6,7,8,9,10])
stack=torch.stack((x,y))
print(stack,stack.shape)
stack1=torch.stack((x,y),0)
print(stack1,stack1.shape)
stack2=torch.stack((x,y),1)
print(stack2,stack2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
tensor([1, 2, 3, 4, 5, 6]) torch.Size([6])
torch.Size([3, 1, 4])
tensor([[[5, 3, 1, 4]],

        [[1, 3, 2, 8]],

        [[1, 2, 2, 7]]])
tensor([[5, 3, 1, 4],
        [1, 3, 2, 8],
        [1, 2, 2, 7]])
torch.Size([3, 4])
tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]) torch.Size([2, 3, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]) torch.Size([6, 1])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) torch.Size([2, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) torch.Size([2, 5])
tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]) torch.Size([5, 2])


In [66]:
#q2
#permute = rotating the dimension of the tensor
print(rand_tensor,rand_tensor.shape)
permute_tensor=torch.permute(rand_tensor,(1,0,2))
print(permute_tensor, permute_tensor.shape)

tensor([[[5, 3, 1, 4]],

        [[1, 3, 2, 8]],

        [[1, 2, 2, 7]]]) torch.Size([3, 1, 4])
tensor([[[5, 3, 1, 4],
         [1, 3, 2, 8],
         [1, 2, 2, 7]]]) torch.Size([1, 3, 4])


In [74]:
#q3
print(tensor,tensor.shape)
indices=torch.tensor([1,2])
index_tensor=torch.index_select(tensor,1,indices)
print(index_tensor,index_tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[2, 3],
        [5, 6]]) torch.Size([2, 2])


In [76]:
#q4
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
arr_to_tensor=torch.from_numpy(a)
print(arr_to_tensor, arr_to_tensor.shape)
tensor_to_arr=arr_to_tensor.numpy()
print(tensor_to_arr, tensor_to_arr.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
[[1 2 3]
 [4 5 6]] (2, 3)


In [77]:
#q5
random=torch.randint(1,10,(7,7))
random

tensor([[6, 7, 4, 6, 2, 3, 5],
        [1, 1, 7, 2, 1, 7, 5],
        [2, 6, 8, 1, 6, 6, 4],
        [1, 9, 9, 9, 4, 1, 4],
        [1, 6, 6, 3, 4, 4, 2],
        [4, 5, 7, 8, 5, 6, 7],
        [2, 1, 3, 3, 9, 4, 8]])

In [86]:
#q6
sec_tensor=torch.randint(1,10,(1,7))
print(sec_tensor)
mul_tensor=torch.matmul(random,sec_tensor.T)
print(mul_tensor, mul_tensor.shape)

tensor([[3, 5, 1, 4, 4, 4, 4]])
tensor([[121],
        [ 75],
        [112],
        [129],
        [ 91],
        [148],
        [110]]) torch.Size([7, 1])


In [84]:
#Q7
tensor
tensor_to_gpu=tensor.to(device)
print("tensor on gpu: ",tensor_to_gpu)

tensor on gpu:  tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')


In [87]:
#q8
adjusted_tensor = torch.reshape(sec_tensor,(7,1))
mulmat_tensor=torch.matmul(random,adjusted_tensor)
print(mulmat_tensor, mulmat_tensor.shape)

tensor([[121],
        [ 75],
        [112],
        [129],
        [ 91],
        [148],
        [110]]) torch.Size([7, 1])


In [88]:
#q9
print(tensor_to_gpu.max())
print(tensor_to_gpu.min())

tensor(6, device='cuda:0')
tensor(1, device='cuda:0')


In [89]:
#q10
print(torch.argmin(tensor_to_gpu))
print(torch.argmax(tensor_to_gpu))

tensor(0, device='cuda:0')
tensor(5, device='cuda:0')


In [97]:
#q11
torch.manual_seed(7)
random_tensor=torch.randint(1,7,(1,1,1,10))
new_tensor=random_tensor.squeeze()
print(random_tensor,new_tensor)
print(random_tensor.shape,new_tensor.shape)


tensor([[[[4, 5, 2, 3, 2, 4, 6, 6, 5, 6]]]]) tensor([4, 5, 2, 3, 2, 4, 6, 6, 5, 6])
torch.Size([1, 1, 1, 10]) torch.Size([10])
